sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
before_install: gem install bundler -v 1.16.1
script:
  - bundle exec rake spec
