sudo: false
language: ruby
rvm:
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
matrix:
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/activerecord_4.2.gemfile
script:
  - bundle exec rake spec
